print("haritha")
print("welcome")
print("sujith naidu")
print('dont change attitude hust fuck off')
print(" if the life belomgs us ")
print(" why these kolavari ")
print(" eee back bench rock str sujitj naidu")
